version: "3.3"

services: 
    bot:
        build: ./bot
        restart: unless-stopped
        env_file: 
            - .env
        volumes: 
            - ./bot:/app:Z
        depends_on:
            - database
        

    database:
        image:  postgres:12
        env_file:
            - .env
        volumes:
            - ./database/schema/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: 
            - 5442:5432
